### ISSUE TITLE
Import from a legacy query plan does not work

### ISSUE THREAD

**Issue by MehdiEnnaime** [activeviam/activeviam.github.io#2]
When using the tool with the following query plan, nothing happens :

[queryplan.txt](https://github.com/activeviam/activeviam.github.io/files/4546992/queryplan.txt)

AP version : 5.8.9

**Comment by OPeyrusse** [comment]
The loading from v1 was missing the generation of a query summary, which is the first view in the latest version.
I have a PR fixing this.

**Comment by OPeyrusse** [comment]
This is now fixed. Enjoy :)
